---
output:
  html_document:
    toc: no
    toc_depth: 3
    toc_float:
      collapsed: yes
---
<style>
  .head-1 {
    font-family: Times New Roman;
    font-size: 32px;
    font-weight: bold;
    text-align: center;
  }
  .head-2 {
    font-family: Times New Roman;
    font-size: 16px;
    font-weight: normal;
    text-align: center;
  }
  
  .content {
    font-family: Times New Roman;
    font-weight: bold;
    font-size: 32px;
    margin-left: 0;
    width: 100%;
  }
  
  .content-2 {
    font-family: Times New Roman;
    font-size: 20px;
    font-weight: bold;
    margin-left: 0;
    float: left;
    width: 70%;
  }
  
   .content-3 {
    font-family: Times New Roman;
    font-size: 20px;
    font-weight: normal;
    text-align: right;
    margin-right: 0;
    float: right;
    width: 30%;
  }
  
   .content-4 {
    font-family: Times New Roman;
    font-size: 20px;
    font-weight: normal;
    margin-left: 0;
    float: left;
    width: 100%;
    }
    
  li{
  margin-top: 0px;
  margin-bottom: 0px;
  margin-left: 0;
}

  h1{
  font-family: Times New Roman;
}


  hr{
  border: 0px;
  height: 2px;
  margin-top: 0px;
  margin-bottom: 0px;
  background: black;
  background-image: ;
  width: 100%
}
 
</style>

<body bgcolor = "pink">

</br>
<div class="head-1">Wenwen Tan</div>
<div class="head-2">evatan123\@hotmail.com&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;13693193863</div>

<div class="content">Education</div>


<hr/>

<div class="content-2">University of Massachusetts Amherst</div>
<div class="content-3">Sep 2016 - May 2017</div>
<div class="content-4">Major: Biostatistics</div>
<div class="content-4">Scholarship: David Hosmer Award</div>
<div class="content-2">Wuhan University</div>
<div class="content-3">Sep 2012 - May 2016</div>
<div class="content-4">Major: Pharmacy</div>

<div class="content">Work Experience</div>
<hr/>
<div class="content-2">eChinaCash Network Technology Co.,Ltd(US-incorporated)</div>

<div class="content-3">Jan 2018 - present</div>

<div class = "content-4">
- Completed daily, weekly and monthly data analysis report using excel(data from gas satations of Sinopec)
- Provided data support and effective suggestion for marketing department
- Carried out special case study and wrote case report regularly
- Responded to  special data requirement from customers and mined the data to make better analysis and provided good suggestion for new projects and new processes
</div>

<div class = "content-2">Xian-Janssen Pharmaceutical Ltd.</div>
<div class = "content-3">Oct 2017 - Jan 2018</div>
<div class = "content-4">
- Followed up the process of meetings and collected related materials.
- Analyzed the data related with the meetings hosted.
- Made charts and recorded the process of meetings.
- Archived the document related to the meetings hosted.
</div>

<div class="content">Research Experience</div>
<hr/>

<div class="content-2">University of Jena</div>
<div class="content-3">Oct 2015 - May 2016</div>
<div class = "content-4">
- Identified the anti- inflammatory effect of two series of sompounds.
- Carried out density centrifugation technology to separate cells from blood coats.
- Adopted MTT assays to test cell activities after the additions of compounds.
- Conducted 5- lipoxygenase assays to simulate the 5- lipoxygenase pathway in human cells and used solid phase extraction to separate the metabolic products.
- Analyzed the experiment data by GraphPad Prism 4 and Microsoft Office Excel.
</div>


</body>


